"""Created Lottery, Participant, Ballot and WinningBallot tables

Revision ID: aa03401e3a2e
Revises: 
Create Date: 2025-05-12 15:01:54.391578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa03401e3a2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lottery_draw_date'), 'lottery', ['draw_date'], unique=False)
    op.create_table('participant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_table('ballot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('lottery_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lottery.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winning_ballot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ballot_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winning_ballot')
    op.drop_table('ballot')
    op.drop_table('participant')
    op.drop_index(op.f('ix_lottery_draw_date'), table_name='lottery')
    op.drop_table('lottery')
    # ### end Alembic commands ###
